### ISSUE TITLE
Tests Broken

### ISSUE THREAD

**Issue by burhan** [django/django-localflavor#230]
Tests are no longer working on the master branch:

```
Check Information
=================
         Started: 2016-05-06 19:42:45.206145
        Finished: 2016-05-06 19:43:05.170191
      Time Taken: 19.96 seconds
       Formatter: grouped
        Profiles: .landscape.yml, doc_warnings, strictness_veryhigh, no_member_warnings
      Strictness: from profile
  Libraries Used: django
       Tools Run: dodgy, mccabe, pep257, pep8, profile-validator, pyflakes, pylint
  Messages Found: 1024

isort develop-inst-nodeps: /home/burhan/work/projects/django-localflavor
isort installed: Django==1.9.6,-e git+git@github.com:burhan/django-localflavor.git@df39beaa6f21906c13ae6be7d020d39761c2e4b1#egg=django_localflavor,isort==4.2.5
isort runtests: PYTHONHASHSEED='4075836488'
isort runtests: commands[0] | isort --recursive --line-width 120 --check /home/burhan/work/projects/django-localflavor/localflavor /home/burhan/work/projects/django-localflavor/tests
Skipped 68 files
py27-1.7 develop-inst-nodeps: /home/burhan/work/projects/django-localflavor
py27-1.7 installed: coverage==3.7.1,Django==1.7.11,-e git+git@github.com:burhan/django-localflavor.git@df39beaa6f21906c13ae6be7d020d39761c2e4b1#egg=django_localflavor,flake8==2.2.5,invoke==0.11.1,mccabe==0.4.0,pep8==1.7.0,pyflakes==1.2.1,six==1.10.0
py27-1.7 runtests: PYTHONHASHSEED='4075836488'
py27-1.7 runtests: commands[0] | invoke test
Python version: 2.7.11+ (default, Apr 17 2016, 14:00:29) 
[GCC 5.3.1 20160413]
Process Process-5:
Traceback (most recent call last):
  File "/usr/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/lib/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "/home/burhan/work/projects/django-localflavor/.tox/py27-1.7/local/lib/python2.7/site-packages/flake8/reporter.py", line 73, in process_main
    self._process_main()
  File "/home/burhan/work/projects/django-localflavor/.tox/py27-1.7/local/lib/python2.7/site-packages/flake8/reporter.py", line 49, in _process_main
    self.input_file(filename)
  File "/home/burhan/work/projects/django-localflavor/.tox/py27-1.7/local/lib/python2.7/site-packages/flake8/engine.py", line 96, in input_file
    return fchecker.check_all(expected=expected, line_offset=line_offset)
  File "/home/burhan/work/projects/django-localflavor/.tox/py27-1.7/local/lib/python2.7/site-packages/pep8.py", line 1574, in check_all
    self.check_ast()
  File "/home/burhan/work/projects/django-localflavor/.tox/py27-1.7/local/lib/python2.7/site-packages/pep8.py", line 1520, in check_ast
    checker = cls(tree, self.filename)
  File "/home/burhan/work/projects/django-localflavor/.tox/py27-1.7/local/lib/python2.7/site-packages/flake8/_pyflakes.py", line 43, in __init__
    withDoctest=self.withDoctest)
  File "/home/burhan/work/projects/django-localflavor/.tox/py27-1.7/local/lib/python2.7/site-packages/pyflakes/checker.py", line 416, in __init__
    self.handleChildren(tree)
  File "/home/burhan/work/projects/django-localflavor/.tox/py27-1.7/local/lib/python2.7/site-packages/pyflakes/checker.py", line 738, in handleChildren
    self.handleNode(node, tree)
  File "/home/burhan/work/projects/django-localflavor/.tox/py27-1.7/local/lib/python2.7/site-packages/pyflakes/checker.py", line 785, in handleNode
    handler(node)
  File "/home/burhan/work/projects/django-localflavor/.tox/py27-1.7/local/lib/python2.7/site-packages/pyflakes/checker.py", line 1164, in IMPORTFROM
    node.module, alias.name)
  File "/home/burhan/work/projects/django-localflavor/.tox/py27-1.7/local/lib/python2.7/site-packages/pyflakes/checker.py", line 212, in __init__
    full_name = module + '.' + self.real_name
TypeError: unsupported operand type(s) for +: 'NoneType' and 'str'
```

I believe this has to do with [`pyflakes` bug #1560134](https://bugs.launchpad.net/pyflakes/+bug/1560134) the fix has been pushed, but the tests are not updated with the latest version.

**Comment by benkonrath** [comment]
pyflakes is being pulled in through prospector. Perhaps it would be a good idea to pin prospector to a specific version. This problem isn't critical just yet because we're not enforcing a style with prospector just yet.

**Comment by benkonrath** [comment]
@burhan I just realized that you're having problem locally. How are you running the tests to get this error? Does it work for you to run the tests with tox?

**Comment by burhan** [comment]
I simply cloned the repo, created a new virtualenv, did pip install tox,
and then typed tox.

**Comment by burhan** [comment]
I temporarily resolved this issue by adding `--without-tool pyflakes` to `tox.ini` for the prospector configuration:

```
[testenv:prospector]
deps = prospector
basepython = python2.7
commands = prospector --zero-exit --without-tool pyflakes {toxinidir}
```

**Comment by burhan** [comment]
Travis builds are also failing now.

**Comment by burhan** [comment]
Temporary fix is to disable the `pyflakes` tasks in `tasks.py`

**Comment by benkonrath** [comment]
I didn't realize that flake8 is run in the test task independently of the prospector job. I'll try to fix this.

**Comment by benkonrath** [comment]
See the comment in #233 about the fix not working.

**Comment by benkonrath** [comment]
@burhan I see that the tests in your pull requests are now passing. Are you still having issues with the tests failing on your computer?

**Comment by benkonrath** [comment]
The tests appear to be working properly now.
