### ISSUE TITLE
Django-Localflavor 1.6.2 incompatible with Django 2.0 in regionalized items for Brazil

### ISSUE THREAD

**Issue by estevaobarbosa** [django/django-localflavor#323]
The Django-Localflavor 1.6.2 package is incompatible with Django 2.0 in the regionalized items for Brazil. When Django returns to version 1.11, the Localflavor routines return to run. 

Send down the source code and the error message:

Thanks,

Estevao Lemos Barbosa 

===========
Code:
===========
from django import forms
from localflavor.br.forms import BRCPFField, BRCNPJField, BRPhoneNumberField, BRZipCodeField
from .models import UsuarioPrincipal, Usuarios

class UsuariosForm(forms.ModelForm):
    cpf= BRCPFField()

    class Meta:
        model = Usuarios
        fields = '__all__'

============
Error Message:
===========
"C:\Program Files\JetBrains\IntelliJ IDEA 2017.3\bin\runnerw.exe" C:\EB\Programas\Python\pecamaisaqui\pecamaisaqui\venv\Scripts\python.exe C:/EB/Programas/Python/pecamaisaqui/pecamaisaqui/manage.py runserver localhost:8000
Performing system checks...

Unhandled exception in thread started by <function check_errors.<locals>.wrapper at 0x000001BE6BBFFBF8>
Traceback (most recent call last):
  File "C:\EB\Programas\Python\pecamaisaqui\pecamaisaqui\venv\Lib\site-packages\django\utils\autoreload.py", line 225, in wrapper
    fn(*args, **kwargs)
  File "C:\EB\Programas\Python\pecamaisaqui\pecamaisaqui\venv\Lib\site-packages\django\core\management\commands\runserver.py", line 120, in inner_run
    self.check(display_num_errors=True)
  File "C:\EB\Programas\Python\pecamaisaqui\pecamaisaqui\venv\Lib\site-packages\django\core\management\base.py", line 364, in check
    include_deployment_checks=include_deployment_checks,
  File "C:\EB\Programas\Python\pecamaisaqui\pecamaisaqui\venv\Lib\site-packages\django\core\management\base.py", line 351, in _run_checks
    return checks.run_checks(**kwargs)
  File "C:\EB\Programas\Python\pecamaisaqui\pecamaisaqui\venv\Lib\site-packages\django\core\checks\registry.py", line 73, in run_checks
    new_errors = check(app_configs=app_configs)
  File "C:\EB\Programas\Python\pecamaisaqui\pecamaisaqui\venv\Lib\site-packages\django\core\checks\urls.py", line 40, in check_url_namespaces_unique
    all_namespaces = _load_all_namespaces(resolver)
  File "C:\EB\Programas\Python\pecamaisaqui\pecamaisaqui\venv\Lib\site-packages\django\core\checks\urls.py", line 57, in _load_all_namespaces
    url_patterns = getattr(resolver, 'url_patterns', [])
  File "C:\EB\Programas\Python\pecamaisaqui\pecamaisaqui\venv\Lib\site-packages\django\utils\functional.py", line 36, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "C:\EB\Programas\Python\pecamaisaqui\pecamaisaqui\venv\Lib\site-packages\django\urls\resolvers.py", line 536, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "C:\EB\Programas\Python\pecamaisaqui\pecamaisaqui\venv\Lib\site-packages\django\utils\functional.py", line 36, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "C:\EB\Programas\Python\pecamaisaqui\pecamaisaqui\venv\Lib\site-packages\django\urls\resolvers.py", line 529, in urlconf_module
    return import_module(self.urlconf_name)
  File "C:\EB\Programas\Python\pecamaisaqui\pecamaisaqui\venv\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 978, in _gcd_import
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load
  File "<frozen importlib._bootstrap>", line 950, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 655, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 205, in _call_with_frames_removed
  File "C:\EB\Programas\Python\pecamaisaqui\pecamaisaqui\pecamaisaqui\urls.py", line 13, in <module>
    url(r'^usuarios/',include('pecamaisaqui.usuarios.urls', namespace='usuarios')),
  File "C:\EB\Programas\Python\pecamaisaqui\pecamaisaqui\venv\Lib\site-packages\django\urls\conf.py", line 34, in include
    urlconf_module = import_module(urlconf_module)
  File "C:\EB\Programas\Python\pecamaisaqui\pecamaisaqui\venv\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 978, in _gcd_import
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load
  File "<frozen importlib._bootstrap>", line 950, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 655, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 205, in _call_with_frames_removed
  File "C:\EB\Programas\Python\pecamaisaqui\pecamaisaqui\pecamaisaqui\usuarios\urls.py", line 4, in <module>
    from .views import (
  File "C:\EB\Programas\Python\pecamaisaqui\pecamaisaqui\pecamaisaqui\usuarios\views.py", line 8, in <module>
    from .forms import UsuariosForm
  File "C:\EB\Programas\Python\pecamaisaqui\pecamaisaqui\pecamaisaqui\usuarios\forms.py", line 7, in <module>
    class UsuariosForm(forms.ModelForm):
  File "C:\EB\Programas\Python\pecamaisaqui\pecamaisaqui\pecamaisaqui\usuarios\forms.py", line 8, in UsuariosForm
    cpf= BRCPFField()
  File "C:\EB\Programas\Python\pecamaisaqui\pecamaisaqui\venv\Lib\site-packages\localflavor\br\forms.py", line 133, in __init__
    super(BRCPFField, self).__init__(max_length, min_length, *args, **kwargs)
  File "C:\EB\Programas\Python\pecamaisaqui\pecamaisaqui\venv\Lib\site-packages\localflavor\compat.py", line 16, in __init__
    super(EmptyValueCompatMixin, self).__init__(*args, **kwargs)
TypeError: __init__() takes 1 positional argument but 3 were given

**Comment by benkonrath** [comment]
The master branch works with Django 2.0. See #322 for details about when this will be released.

Can you test with the master branch to confirm it's working for you?

**Comment by benkonrath** [comment]
django-localflavor 2.0 has just been released. I'm assuming that that using the 2.0 release will fix your problem. If you still have this problem with django-localflavor 2.0, please reopen this issue.

**Comment by estevaobarbosa** [comment]
The error is solved. Thank you.
